services:
  db:
    image: postgres:14.17
    restart: always
    environment:
      # For docker set up of db.
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # For postgres itself.
      - PGUSER=postgres
      - PGPASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local
  