FROM node:22-alpine AS base
WORKDIR /usr/local/app

# This env var is necessary for the client to be built - the value gets baked in.
# Docker compose envs are not in existence when this image is getting built.
ARG VITE_SERVER_URL

COPY . .
# This project uses pnpm instead of npm. No npm package lockfiles, just pnpm-lock.
RUN npm install --global pnpm
# There is no clean-install on pnpm so just use normal.
# Not sure there is actually any benefit to clean installing within the dockerfile.
# Surely the node image is clean anyway and there is nothing to clear out?
RUN pnpm install
RUN npx prisma generate
RUN pnpm run build

# Migrate has to be part of start up command. Since in docker compose this service will
# depend on the db service, we can be sure it will be running when npm run migrate happens.
CMD ["sh", "-c", "pnpm run migrate && npx vitest -c ./vitest.int.config.js"]
